// <auto-generated />
namespace VotingApplication.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class RenameAnonymousVoting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenameAnonymousVoting));
        
        string IMigrationMetadata.Id
        {
            get { return "201503091629236_RenameAnonymousVoting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
