// <auto-generated />
namespace VotingApplication.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class AddManageGuidToBallot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddManageGuidToBallot));
        
        string IMigrationMetadata.Id
        {
            get { return "201503300852057_AddManageGuidToBallot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
