// <auto-generated />
namespace VotingApplication.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ExpiryDate_Utc : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ExpiryDate_Utc));
        
        string IMigrationMetadata.Id
        {
            get { return "201505220738506_ExpiryDate_Utc"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
